[package]
name = "symboscript-interpreter"
version = "0.6.3"
edition = "2021"
authors = ["artegoser"]
license = "MIT"
description = "SymboScript interpreter"
repository = "https://github.com/artegoser/SymboScript"
homepage = "https://github.com/artegoser/SymboScript/tree/main/interpreter"
documentation = "https://github.com/artegoser/SymboScript/blob/master/doc/main.md"
keywords = ["programming-language", "interpreter", "symbolic", "symboscript"]
categories = ["compilers"]

[dependencies]
symboscript-types = { path = "../types", version = "0.9.0", features = [
  "interpreter",
] }
symboscript-utils = { path = "../utils", version = "0.6.3" }
symboscript-parser = { path = "../parser", version = "0.8.2" }
symboscript-optimizer = { path = "../optimizer", version = "0.7.4" }

clap = { version = "4.4.12", features = ["derive"] }
