[package]
name = "symboscript-interpreter"
version = "0.0.0"
edition = "2021"
authors = ["artegoser"]
license = "MIT"
description = "SymboScript interpreter"
repository = "https://github.com/artegoser/SymboScript"
homepage = "https://github.com/artegoser/SymboScript/tree/main/interpreter"
documentation = "https://github.com/artegoser/SymboScript/blob/master/doc/main.md"
keywords = ["programming-language", "interpreter", "symbolic", "symboscript"]
categories = ["compilers"]
